version: "3.7"

services:
  # consul:
  #   image: consul
  #   container_name: consul
  #   restart: unless-stopped
  #   networks:
  #     - myspot
  #   ports:
  #     - 8500:8500
  #   # volumes:
  #   #   - consul:/consul/data

  # fabio:
  #   image: fabiolb/fabio
  #   container_name: fabio
  #   restart: unless-stopped
  #   environment:
  #   - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
  #   networks:
  #     - myspot
  #   ports:
  #   - 9998:9998
  #   - 9999:9999

  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    networks:
      - myspot
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    networks:
      - myspot
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    # volumes: 
    #   - rabbitmq:/var/lib/rabbitmq

networks:
  myspot:
    name: myspot-network

volumes:
  # consul:
  #   driver: local
  # grafana:
  #   driver: local
  postgres:
    driver: local
  # prometheus:
  #   driver: local
  # rabbitmq:
  #   driver: local
  # seq:
  #   driver: local
  